package main

import (
	"authApp/auth"
	"authApp/cmd/data"
	"context"
	"fmt"
	"google.golang.org/grpc"
	"log"
	"net"
)

var grpcPort = "50001"

// AuthServer initialize a new grpc server
type AuthServer struct {
	auth.UnimplementedAuthServiceServer
	Model data.Models
}

// Authenticate by req from AuthRequest from code that generated by grpc
func (as *AuthServer) Authenticate(ctx context.Context, req *auth.AuthRequest) (*auth.AuthResponse, error) {
	input := req.GetAuthEntry()

	authEntry := data.Models{
		User: data.User{
			Email:    input.Email,
			Password: input.Password,
		},
	}

	// check if password matches in database
	ok, err := as.Model.User.PasswordMatches(authEntry.User.Password)
	if err != nil || ok == false {
		res := &auth.AuthResponse{
			Result: "failed",
		}
		return res, err
	}

	res := &auth.AuthResponse{
		Result: "logged in",
	}

	return res, nil
}

// listening for grpc connection and check for errors that can happen while starting the grpc server
func (app *Config) grpcListen() {
	lis, err := net.Listen("tcp", fmt.Sprintf(":%s", grpcPort))
	if err != nil {
		log.Fatalf("failes to listen for grpc %v", err)
	}

	server := grpc.NewServer()

	auth.RegisterAuthServiceServer(server, &AuthServer{
		Model: app.Models,
	})
	log.Println("grpc server started on port: ", grpcPort)

	if err := server.Serve(lis); err != nil {
		log.Fatalf("unable to listen for grpc server %v", err)
	}
}
