// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: shortner.proto

package shortner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShortnerServiceClient is the client API for ShortnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortnerServiceClient interface {
	ShortenUrl(ctx context.Context, in *ShortnerRequest, opts ...grpc.CallOption) (*ShortnerResponse, error)
}

type shortnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortnerServiceClient(cc grpc.ClientConnInterface) ShortnerServiceClient {
	return &shortnerServiceClient{cc}
}

func (c *shortnerServiceClient) ShortenUrl(ctx context.Context, in *ShortnerRequest, opts ...grpc.CallOption) (*ShortnerResponse, error) {
	out := new(ShortnerResponse)
	err := c.cc.Invoke(ctx, "/shortner.shortnerService/ShortenUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortnerServiceServer is the server API for ShortnerService service.
// All implementations must embed UnimplementedShortnerServiceServer
// for forward compatibility
type ShortnerServiceServer interface {
	ShortenUrl(context.Context, *ShortnerRequest) (*ShortnerResponse, error)
	mustEmbedUnimplementedShortnerServiceServer()
}

// UnimplementedShortnerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShortnerServiceServer struct {
}

func (UnimplementedShortnerServiceServer) ShortenUrl(context.Context, *ShortnerRequest) (*ShortnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShortenUrl not implemented")
}
func (UnimplementedShortnerServiceServer) mustEmbedUnimplementedShortnerServiceServer() {}

// UnsafeShortnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortnerServiceServer will
// result in compilation errors.
type UnsafeShortnerServiceServer interface {
	mustEmbedUnimplementedShortnerServiceServer()
}

func RegisterShortnerServiceServer(s grpc.ServiceRegistrar, srv ShortnerServiceServer) {
	s.RegisterService(&ShortnerService_ServiceDesc, srv)
}

func _ShortnerService_ShortenUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortnerServiceServer).ShortenUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortner.shortnerService/ShortenUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortnerServiceServer).ShortenUrl(ctx, req.(*ShortnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortnerService_ServiceDesc is the grpc.ServiceDesc for ShortnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shortner.shortnerService",
	HandlerType: (*ShortnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShortenUrl",
			Handler:    _ShortnerService_ShortenUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shortner.proto",
}
